def RecordFieldsValidation():
    return [\
            ['accession number', ["^\d{4}-\d{3}$"]],\
            ['department', []],\
            ['summary', []],\
            ['fiscalYear', []],\
            ['ark', ["^\w{13}$"]],\
            ['collection', []],\
            ['eadid', []],\
            ['spanDate', []],\
            ['type', []],\
            ['prc', []],\
            ['rights', []],\
            ['restrictions', []],\
            ['restrictionComment', []],\
            ['totalDigitalSize', []],\
            ['digitalCondition', []],\
            ['totalPhysicalSize', []],\
            ['physicalCondition', []],\
            ['physicalLocation', []],\
            ['fileRecDate', []],\
            ['fileInfo', []],\
            ['fileAccDate', []],\
            ['fileTransDate', []],\
            ['fileBackDate', []],\
            ['fileDelDate', []],\
            ['donor', []],\
            ['source', []],\
            ['origin', []],\
            ['permittedUseAccess', []],\
            ['permittedUseDiscover', []],\
            ['adminNote', []],\
            ['priority', []],\
            ['existingDigitalCollection', []],\
            ['dasRecDate', []],\
            ['recLetter', []],\
            ['sendInv', []],\
            ['giftAckOrDeed', []],\
            ['access', []],\
            ['recBy', []],\
            ['dasRecBy', []],\
            ['addenda', []],\
            ['physicalMedia', []],\
            ['existingPhysicalCollection', []],\
            ['physicalHasFindingAid', []],\
            ['sentToDASOn', []]\
]
